Code refactor, use modules

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ env:
   LAMBDA_FUNCTION: lambda-terraform
   S3_BUCKET: s3-terraform-083971419667
   S3_BUCKET_TF_STATE: s3-tfstate-083971419667
-  CLOUDFRONT_DISTRIBUTION_ID: E1XEREO1WT2D9H
+  CLOUDFRONT_DISTRIBUTION_ID: E99RBQPV79L7R
   AWS_REGION: us-east-1
 
 jobs:
@@ -102,60 +102,60 @@ jobs:
         
       - name: Static Analysis Report(pylint)
         run: |
-          pylint lambda_function.py --output-format=parseable > pylint-report.txt || true
+          pylint *.py --output-format=parseable > pylint-report.txt || true
           echo "===== PYLINT REPORT ====="
           cat pylint-report.txt          
         working-directory: Lambda
 
-  deploy_terraform:
-    needs:
-      - detect_changes
-    if: needs.detect_changes.outputs.terraform == 'true' || needs.detect_changes.outputs.lambda == 'true'
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./Terraform    
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
+  # deploy_terraform:
+  #   needs:
+  #     - detect_changes
+  #   if: needs.detect_changes.outputs.terraform == 'true' || needs.detect_changes.outputs.lambda == 'true'
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: ./Terraform    
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
 
-      - name: Install tfsec
-        run: |
-          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
+  #     - name: Install tfsec
+  #       run: |
+  #         curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
 
-      - uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+  #     - uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ env.AWS_REGION }}
 
-      - name: Setup terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.6.6
+  #     - name: Setup terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.6.6
 
-      - name: Terraform init
-        run: terraform init 
+  #     - name: Terraform init
+  #       run: terraform init 
 
-      - name: Terraform format
-        run: terraform fmt -check
+  #     - name: Terraform format
+  #       run: terraform fmt -check
 
-      - name: Terraform validate
-        run: terraform validate        
+  #     - name: Terraform validate
+  #       run: terraform validate        
 
-      - name: Terraform security scan
-        run: tfsec --minimum-severity MEDIUM
+  #     - name: Terraform security scan
+  #       run: tfsec --minimum-severity LOW .
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -input=false -out planfile
-        continue-on-error: true
+  #     - name: Terraform plan
+  #       id: plan
+  #       run: terraform plan -input=false -out planfile
+  #       continue-on-error: true
       
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1        
+  #     - name: Terraform plan status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1        
 
-      - name: terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false planfile        
+  #     - name: terraform Apply
+  #       # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+  #       run: terraform apply -auto-approve -input=false planfile        
